### ISSUE TITLE
Mostrar os relacionamentos entre recursos educacionais tanto na lista do resultado de busca como no detalhemento do registro

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/oer-wp-plugin#12]
Podemos adotar a mesma solução dada para o projeto de legislação.
Exemplo:
http://sites.bvsalud.org/legislacion/factores-de-riesgo/resource/?id=leisref.act.1487
![image](https://user-images.githubusercontent.com/1226218/44746829-dacc8480-aae1-11e8-8d91-6f7b1a67f96f.png)
Um recurso educacional que já tem relacionamento no metadado é http://sites.bvsalud.org/rea/bireme/busca/resource/?id=oer.oer.840

**Comment by viniciusandrade** [comment]
Este issue possui a seguinte dependência https://github.com/bireme/fi-admin/issues/642

**Comment by viniciusandrade** [comment]
@cordeirofilho 

Dependência implementada, liberado para ajuste no plugin usando os elementos **relationship_active** e **relationship_passive**.

**Comment by viniciusandrade** [comment]
Código incorporado e site em produção atualizado (http://sites.bvsalud.org/rea/repositorio/)

**Comment by renatomurasaki** [comment]
Precisa fazer algo nas demais instâncias de rea? Vejo que, por exemplo, em rea/bireme, o label do relacionamento na lista de resultado de busca está em inglês e ao ver o detalhamento está em português

**Comment by renatomurasaki** [comment]
Outra questão: o tamanho da fonte nas sessões objetivos e descrição estão desproporcionais com o tamanho do título do REA. Sugiro que o relacionamento esteja em destaque separado dos demais elementos de dados. @cordeirofilho poderia propor um novo design nessa página de detalhamento do REA?

**Comment by viniciusandrade** [comment]
@renatomurasaki 

Ajustei o tamanho da fonte para ficar proporcional aos demais elementos da página. 

Quanto ao idioma dos rótulos não identifiquei o problema pois nos meus testes estão sempre aparecendo no idioma espanhol.

@cordeirofilho 

O novo design para a página pode ser proposto para o issue #6
