### ISSUE TITLE
Colocar os sites.bvsalud.org/rea/* em 3 idiomas

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/oer-wp-plugin#13]

**Comment by marcoslmori** [comment]
Por favor, validar @renatomurasaki os subsites do repositório
 
O site principal está sendo desenvolvido fora do tema padrão do plugin da BVS

**Comment by marcoslmori** [comment]
Atividade efetuada, 

O repositório geral ficou como subsite designado como general para que mantivesse de forma padronizado a navegação por idiomas. 

Ficando pendente, no sentido que não foi definida  uma solução para que o título fiquem em duas linhas.
