### ISSUE TITLE
Atualizar índice do web service fi-admin-oer, por cuenta de la actualización de la lista de licencias

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/oer-wp-plugin#14]
Los nombres de las licencias CC fueron armonizados de acuerdo con el sitio https://creativecommons.org/licenses, en inglés, portugués y español. También fueron creadas las licencias IGO, utilizadas por OPS/OMS.

**Comment by viniciusandrade** [comment]
Coleção re-indexada.
