### ISSUE TITLE
Criar novos clusters

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/oer-wp-plugin#2]
Clusters adicionais:
Tipo de Curso
Tipo de Recurso Técnico
Formato
Tipo de recurso de aprendizagem
Contexto de aprendizagem
Nivel de Agregação
Audiencia
Licença de direitos

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/oer-wp-plugin/commit/4ef2fad2fb45239575e7896755e2ad9ef2e096e1 

Atualizado para todas as instâncias de http://sites.bvsalud.org/rea/
