### ISSUE TITLE
Criar mais uma opção no BreadCrumb do plugin  para voltar para a página de pesquisa

### ISSUE THREAD

**Issue by marcoslmori** [bireme/oer-wp-plugin#21]
![image](https://user-images.githubusercontent.com/10047460/48157983-56079f00-e2b8-11e8-9094-9b97eaa6efb2.png)

**Comment by viniciusandrade** [comment]
@marcoslmori 

Implementado e plugin atualizado em sites.bvsalud.org/rea/ favor validar.

**Comment by marcoslmori** [comment]
validado !!
