### ISSUE TITLE
O embedar do plugin não está aparecendo em instancia que já está com ssl (https) 

### ISSUE THREAD

**Issue by marcoslmori** [bireme/oer-wp-plugin#29]
Exemplo: 

https://sites.bvsalud.org/rea/bireme/busca/

![image](https://user-images.githubusercontent.com/10047460/76625386-e04bbd00-6515-11ea-9617-eb930b9ea8ba.png)

**Comment by viniciusandrade** [comment]
Resolvido em https://github.com/bireme/oer-wp-plugin/commit/1de7867878471bebf86fdc9c24bea320e56c6492 e instância REA atualizada.
