### ISSUE TITLE
Estruturar a visualização do campo descrição dos REA como se faz no resumo das referências bibliográficas tipo LILACS

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/oer-wp-plugin#5]

**Comment by viniciusandrade** [comment]
Para poder nomear corretamente as abas por idioma depende do ajuste https://github.com/bireme/fi-admin/issues/643

**Comment by viniciusandrade** [comment]
@cordeirofilho 

No caso do plugin de REA (oer) o campo de descrição não possui múltiplas ocorrências como é o caso dos registros bibbliográficos.

Portanto para este plugin basta aplicar a  regular expression que adiciona a marca H2 nas partes da descrição referentes a objetivos, conclusões, etc.

Eu abri um ticket separado (https://github.com/bireme/bibliographic-wp-plugin/issues/47) no plugin de registro bibliográfico para que você possa aplicar o esquema de apresentação dos idiomas em tabs diferentes conforme você mostrou que estava trabalhando.

**Comment by cordeirofilho** [comment]
@viniciusandrade  
A formatação com Regular expression está implementada nos campos Objetivos e Descrição.

**Comment by viniciusandrade** [comment]
Código incorporado e site em produção atualizado (http://sites.bvsalud.org/rea/repositorio/)

**Comment by cordeirofilho** [comment]
segue uma tela de prototipo para o layout
![screenshot_2018-09-05 risk factors of non-communicable diseases](https://user-images.githubusercontent.com/460341/45118440-ea297e80-b12e-11e8-80a3-3a0f1fd8647f.png)

**Comment by renatomurasaki** [comment]
Obrigado! Já enviado para contraparte. Aguardando feedback.

Renato
