### ISSUE TITLE
Revisar layout de apresentação dos metadados do REA abaixo do objetivo e da descrição

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/oer-wp-plugin#7]

**Comment by cordeirofilho** [comment]
Segue proposta de layout
![screenshot_2018-09-14 bireme 3](https://user-images.githubusercontent.com/460341/45573981-bf34de00-b844-11e8-92f6-5892ce56c0ac.png)
![screenshot_2018-09-14 bireme 2](https://user-images.githubusercontent.com/460341/45573983-bf34de00-b844-11e8-8692-29ddef695bdf.png)

**Comment by renatomurasaki** [comment]
Me parece muito boa a proposta. Acho que precisa dar uma solução para o descritor DeCS que ficou solto dentro da caixa de Detalhes.
Sugiro padronizar essa forma de visualizar nos demais plug-ins, começando pelo biblioref.
Favor testar responsividade.

Sent from my iPhone

On 14 Sep 2018, at 17:37, Roberto Cordeiro Filho <notifications@github.com<mailto:notifications@github.com>> wrote:


Segue proposta de layout
[screenshot_2018-09-14 bireme 3]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F460341%2F45573981-bf34de00-b844-11e8-92f6-5892ce56c0ac.png&data=02%7C01%7Cmurasaki%40paho.org%7C1884452534664f91764708d61a81d650%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636725542294195405&sdata=HinR7e2uXWceKWj6tOvlGUv%2FAotJtExAy%2FDTirP56vM%3D&reserved=0>
[screenshot_2018-09-14 bireme 2]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F460341%2F45573983-bf34de00-b844-11e8-8692-29ddef695bdf.png&data=02%7C01%7Cmurasaki%40paho.org%7C1884452534664f91764708d61a81d650%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636725542294205418&sdata=Av5nPbw%2BudlJ0TARzhgjrN05AnFEWx%2B%2BciSRq%2FNt13A%3D&reserved=0>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Foer-wp-plugin%2Fissues%2F7%23issuecomment-421477528&data=02%7C01%7Cmurasaki%40paho.org%7C1884452534664f91764708d61a81d650%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636725542294205418&sdata=x9AXJ1TN6mxezfMTmnDEAPebcY91V7tia9Ebg%2Bxcpy8%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABK16gJ4o7zugdLQ03Idgx0WBSUqxPmxks5ubBNwgaJpZM4VEa2e&data=02%7C01%7Cmurasaki%40paho.org%7C1884452534664f91764708d61a81d650%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636725542294215418&sdata=%2Bt%2BPi3vcYJj2GNVJ7Y9N3FnrCwn530kXEZ9lnWogir8%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by viniciusandrade** [comment]
Ajuste incorporado no plugin via https://github.com/bireme/oer-wp-plugin/commit/fede0dfd97c8bee246a65680dc26a51c35dbf7a5
