### ISSUE TITLE
Criar rodapé com links para os Termos e Condições de Uso e Política de Privacidade

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/oer-wp-plugin#8]
Utilizar como padrão o site do RedETSA/BRISA

**Comment by marcoslmori** [comment]
http://sites.bvsalud.org/factores-de-riesgo/
http://sites.bvsalud.org/rea/
http://sites.bvsalud.org/gcrhs
http://sites.bvsalud.org/memoria-azul

**Comment by marcoslmori** [comment]
Documentado em:  http://wiki.bireme.org/intranet/index.php/Politica_de_privacidade-Termos_condições_de_uso

http://sites.bvsalud.org/factores-de-riesgo/
http://sites.bvsalud.org/rea/
http://sites.bvsalud.org/gcrhs - **[Feito]**
http://sites.bvsalud.org/memoria-azul

**Comment by marcoslmori** [comment]
http://sites.bvsalud.org/factores-de-riesgo/
-- feito em http://sites.bvsalud.org/legislacion/factores-de-riesgo/ [ok]
-- **aguardando o redirect**
http://sites.bvsalud.org/rea/**[faltando o ajuste de css]**
http://sites.bvsalud.org/gcrhs - **[Feito]**
http://sites.bvsalud.org/memoria-azul **[somente em teste]**

**Comment by marcoslmori** [comment]
Atividades efetuadas
